#!/bin/bash

# Times are measured in minutes since midnight,
# so 1110 is 6:30 PM
start_time=1110
submission_file="SUBMISSIONS"
scoreboard_file="SCOREBOARD"
teams="bell_ce digh_ad"
probs="cypher statistics cleaning"

rm $scoreboard_file
for team in $teams
do
	total_penalty_points=0
	total_problems_solved=0
	echo -n "Team $team : " >> $scoreboard_file
	for prob in $probs
	do
		# calculate penalty points for this problem
		submission_count=$(grep "team $team:prob $prob:" $submission_file | wc -l)
		is_correct=$(grep "team $team:prob $prob:1" $submission_file | head -n1 | wc -l)
		wrong_submits=$(expr $submission_count - 1)
		wrong_submit_penalty=$(expr $wrong_submits \* 20)
		wrong_submit_penalty=$(expr $wrong_submit_penalty \* $is_correct)
		submit_minutes=$(grep "team $team:prob $prob:1" $submission_file | head -n1 | cut -d: -f1)
		if [ -z "$submit_minutes" ]
		then
			submit_minutes=$start_time
		fi
		time_penalty=$(expr $submit_minutes - $start_time)
		problem_penalty=$(expr $time_penalty + $wrong_submit_penalty)

		# update running totals
		total_penalty_points=$(expr $total_penalty_points + $problem_penalty)
		total_problems_solved=$(expr $total_problems_solved + $is_correct)

		# update scoreboard
		if [ "$is_correct" -eq "0" ]
		then
			echo -n "X / $submission_count : " >> $scoreboard_file
		else
			echo -n "$problem_penalty / $submission_count : " >> $scoreboard_file
		fi

	done
	echo $total_problems_solved Problems : $total_penalty_points Points >> $scoreboard_file
done

# now, resort the scoreobard file by problems solved and then penalty points
prob_count=$(echo $probs | wc -w)
solution_count_field=$(expr $prob_count + 2)
point_count_field=$(expr $solution_count_field + 1)
sort_params=$(echo "-t: -k$solution_count_field,$solution_count_field"r "-k$point_count_field")
sort $sort_params $scoreboard_file -o $scoreboard_file 
cat $scoreboard_file
