#!/bin/bash

mail_file="CURRENT_PROBLEM"
submission_output="submission.out"

#retrieve all submission from mail
for k in `echo -n | mail | grep SUBMISSION | cut -c5-6 | sort -r`
do
	echo $k | mail > $mail_file

	SUBJECT_LINE=$(grep "Subject:" $mail_file | cut -d: -f3-)
	TEAM=$(echo $SUBJECT_LINE | cut -d: -f1 | tr -d " " | tr '[A-Z]' '[a-z]')
	PROB=$(echo $SUBJECT_LINE | cut -d: -f2 | tr -d " " | tr '[A-Z]' '[a-z]')
	LANG=$(echo $SUBJECT_LINE | cut -d: -f3 | tr -d " " | tr '[A-Z]' '[a-z]')
	TIME=$(echo $SUBJECT_LINE | cut -d: -f4 | tr -d " " | tr '[A-Z]' '[a-z]')
	echo "Retrieved submission from $TEAM for $PROB in $LANG at $TIME"

	SRC_FILE=submission
	SRC_FILE="$SRC_FILE.$LANG"
	echo $SRC_FILE

	start_line_number=`grep 'Status: ' -n $mail_file | cut -d: -f1`
	start_line_number=$(expr $start_line_number + 2)
	tail -n+$start_line_number $mail_file | head -n+2 > $SRC_FILE

	# now judge. TODO Add cutoff for running, multiple language support
	python $SRC_FILE < judge/$PROB.judge.in > $submission_output
	JUDGE_RESULTS=$(diff judge/$PROB.judge.out $submission_output)

	SOLVED=0
	if [ -z "$JUDGE_RESULTS" ]
	then
		SOLVED=1
	fi
	echo $TIME:team $TEAM:prob $PROB:$SOLVED >> SUBMISSIONS

	# report to user
	echo -n "\tSolution was correct?: $SOLVED"

	# clean up
	rm -f $submission_output $SRC_FILE $mail_file

	#delete the mail so it won't be rejudged 
	echo "d$k" | mail >> /dev/null
done

echo "Judging finished"

