#!/bin/bash

# the judge for the contest (essentially the email for the judge)
JUDGE=bell_ce

# loop, getting each of the three required options
while getopts p:t:f: option
do
	case "${option}"
	in
		p) PROB="${OPTARG}";;
		f) FILE="${OPTARG}";;
		t) TEAM="${OPTARG}";;
	esac
done

# if any of the options were empty, or the file didn't have an extension
# print out the 'help' screen
EXT="${FILE##*.}"
if [ -z "$PROB" -o -z "$TEAM" -o -z "$FILE" -o -z "$EXT" ]
then
	echo "submit -p [PROBLEM_NAME] -f [FILE_TO_SEND] -t [TEAM_NAME]"
	echo -e "\tAll fields are required, no spaces in names!"
	exit
fi


# Times are measured in minutes since midnight,
# so 1110 is 6:30 PM
submit_hours=`date +%k`
submit_minutes=`date +%M`
submit_time=`expr $submit_hours \* 60`
submit_time=`expr $submit_time + $submit_minutes`
mail -s "SUBMISSION:$TEAM:$PROB:$EXT:$submit_time" $JUDGE < $FILE

echo "Submission made for team $TEAM on $PROB in $EXT"
