#!/bin/bash

JUDGE=bell_ce

while getopts p:t:f: option
do
	case "${option}"
	in
		p) PROB="${OPTARG}";;
		f) FILE="${OPTARG}";;
		t) TEAM="${OPTARG}";;
	esac
done

# check for non-empties
EXT="${FILE##*.}"
if [ -z "$PROB" -o -z "$TEAM" -o -z "$FILE" -o "$EXT" ]
then
	echo "submit -p [PROBLEM_NAME] -f [FILE_TO_SEND] -t [TEAM_NAME]"
	echo -e "\tAll fields are required, no spaces in names!"
	exit
fi

submit_hours=`date +%k`
submit_minutes=`date +%M`
submit_time=`expr $submit_hours \* 60`
submit_time=`expr $submit_time + $submit_minutes`
mail -s "SUBMISSION:$TEAM:$PROB:$EXT:$submit_time" $JUDGE < $FILE

echo "Submission made for team $TEAM on $PROB in $EXT"
